# main text of home
name: Zoe Wilson
bio: 'Computer Science student at UCCS'

# if it's an external image, update below for true
external-image: true
picture: 'http://i.imgur.com/FqGWLfF.jpg'

url: http://zoewilson.github.io

permalink: /:title/

markdown: kramdown
highlighter: rouge

analytics-google: 'UA-MYANALYTICS'

# if you don't want comments in your posts, set to false
disqus: mydisqus

# if you don't have any of social below, comment the line
facebook: zoewilson789
# twitter: mytwitter
# google: mygoogle
instagram: zoemarie789
# pinterest: mypinterest
linkedin: in/zoewilson789
# youtube: myyoutube
# spotify: myspotify
github: zoewilson
# medium: medium
email: zoewilson789@gmail.com

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

projects: true
about: true
blog: false

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# do you want some animations?
animation: false

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, indigo-gh-pages.zip, Rakefile, screen-shot.png, travis.sh]
